name: facalert
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 
  dio: ^5.4.3+1
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2  
  google_maps_flutter: ^2.10.1
  mime: ^1.0.2
  http_parser: ^4.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  

flutter_launcher_icons:          
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

