# Generated by Django 5.2 on 2025-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_app', '0006_rol_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
