# Generated by Django 5.2 on 2025-04-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias_app', '0007_usuario_latitud_usuario_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='longitud',
        ),
    ]
